-- ==================================================
-- ============ TESTES DE CADASTRO ==================
-- ==================================================

-- TESTE 1: CADASTRO DE CLIENTE
SELECT CADASTRAR_CLIENTE(100, 'CLIENTE TESTE', 'RUA TESTE', '86999999999', 'teste@email.com');
-- TESTE COM E-MAIL INVÁLIDO
SELECT CADASTRAR_CLIENTE(101, 'CLIENTE TESTE', 'RUA TESTE', '86999999999', 'emailinvalido');

-- TESTE 2: CADASTRO DE FUNCIONÁRIO
SELECT CADASTRAR_FUNCIONARIO(100, 'FUNC TESTE', '86999999999', 'func@empresa.com', 'VENDEDOR');
-- TESTE COM TELEFONE INVÁLIDO
SELECT CADASTRAR_FUNCIONARIO(101, 'FUNC TESTE', '86999999', 'func@empresa.com', 'VENDEDOR');

-- TESTE 3: CADASTRO DE PRODUTO
SELECT CADASTRAR_PRODUTO(100, 50, 'PRODUTO TESTE', 10.00, 'TESTE', NULL);
-- TESTE COM COMPONENTE INEXISTENTE
SELECT CADASTRAR_PRODUTO(101, 50, 'PRODUTO TESTE', 10.00, 'TESTE', 999);