-- ==================================================
-- ============ TESTES DE ATUALIZAÇÃO ===============
-- ==================================================

-- TESTE 1: ATUALIZAÇÃO DE ESTOQUE
SELECT ATUALIZAR_ESTOQUE(1, 100);
SELECT * FROM PRODUTO WHERE ID_PRODUTO = 1;

-- TESTE 2: TRIGGER DE ATUALIZAÇÃO DE ESTOQUE EM COMPRAS
INSERT INTO ITEM_COMPRA VALUES (1, 1, 10, 8.00);
SELECT * FROM PRODUTO WHERE ID_PRODUTO = 1;

-- TESTE 3: TRIGGER DE ATUALIZAÇÃO DE ESTOQUE EM PEDIDOS
-- DEVE FALHAR SE ESTOQUE INSUFICIENTE
INSERT INTO ITEM_PEDIDO VALUES (1, 1, 1000, 9.90);