-- ==================================================
-- ====== TESTES DOS GATILHOS AUTOMÁTICOS ===========
-- ==================================================

-- TESTE 1: CÁLCULO AUTOMÁTICO DE TOTAL DE PEDIDO
INSERT INTO ITEM_PEDIDO VALUES (1, 2, 3, 19.90);
SELECT TOTAL FROM PEDIDO WHERE ID_PEDIDO = 1;

-- TESTE 2: DEFINIÇÃO AUTOMÁTICA DE VALOR UNITÁRIO
INSERT INTO ITEM_PEDIDO(ID_PEDIDO, ID_PRODUTO, QUANT) VALUES (1, 3, 2);
SELECT VALOR_UNITARIO FROM ITEM_PEDIDO WHERE ID_ITEM_PEDIDO = (SELECT MAX(ID_ITEM_PEDIDO) FROM ITEM_PEDIDO);

-- TESTE 3: PROCESSAMENTO DE PEDIDO COMPOSTO
INSERT INTO ITEM_PEDIDO(ID_PEDIDO, ID_PRODUTO, QUANT) VALUES (1, 3, 1);
SELECT OBSERVACAO FROM PEDIDO WHERE ID_PEDIDO = 1;