-- ==================================================
-- ================ COMANDOS DROP VIEW ==============
-- ==================================================

DROP VIEW IF EXISTS VW_CLIENTES_ATIVOS;
DROP VIEW IF EXISTS VW_FUNCIONARIOS_ATIVOS;
DROP VIEW IF EXISTS VW_FORNECEDORES_ATIVOS;
DROP VIEW IF EXISTS VW_PRODUTOS_ATIVOS;
DROP VIEW IF EXISTS VW_PEDIDOS_ATIVOS;
DROP VIEW IF EXISTS VW_ITENS_PEDIDO_ATIVOS;
DROP VIEW IF EXISTS VW_COMPRAS_ATIVAS;
DROP VIEW IF EXISTS VW_ITENS_COMPRA_ATIVOS;
DROP VIEW IF EXISTS VW_COMPOSICOES_ATIVAS;

-- ==================================================
-- ================ COMANDOS DROP TABLE =============
-- ==================================================

DROP TABLE IF EXISTS ITEM_COMPRA;
DROP TABLE IF EXISTS COMPRA;
DROP TABLE IF EXISTS ITEM_PEDIDO;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS COMPOSICAO_PRONTA;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS FORNECEDOR;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS CLIENTE;

-- ==================================================
-- ================ COMANDOS SELECT ALL TABLES ======
-- ==================================================

SELECT * FROM CLIENTE;
SELECT * FROM FUNCIONARIO;
SELECT * FROM FORNECEDOR;
SELECT * FROM PRODUTO ORDER BY ID_PRODUTO;
SELECT * FROM PEDIDO;
SELECT * FROM ITEM_PEDIDO;
SELECT * FROM COMPRA;
SELECT * FROM ITEM_COMPRA;
SELECT * FROM COMPOSICAO_PRONTA;

-- ==================================================
-- ================ COMANDOS SELECT ALL VIEWS =======
-- ==================================================

SELECT * FROM VW_CLIENTES_ATIVOS;
SELECT * FROM VW_FUNCIONARIOS_ATIVOS;
SELECT * FROM VW_FORNECEDORES_ATIVOS;
SELECT * FROM VW_PRODUTOS_ATIVOS;
SELECT * FROM VW_PEDIDOS_ATIVOS;
SELECT * FROM VW_ITENS_PEDIDO_ATIVOS;
SELECT * FROM VW_COMPRAS_ATIVAS;
SELECT * FROM VW_ITENS_COMPRA_ATIVOS;
SELECT * FROM VW_COMPOSICOES_ATIVAS;

-- ==================================================
-- ============ FUNÇÕES DE CADASTRO ===================
-- ==================================================
DROP FUNCTION IF EXISTS CADASTRAR_CLIENTE(INT, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS CADASTRAR_FUNCIONARIO(INT, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS CADASTRAR_FORNECEDOR(INT, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS CADASTRAR_PRODUTO(INT, INT, VARCHAR, DECIMAL, VARCHAR, INT);
DROP FUNCTION IF EXISTS CADASTRAR_COMPOSICAO(INT, INT, INT, DECIMAL, INT);

-- ==================================================
-- ============ FUNÇÕES DE ATUALIZAÇÕES ===================
-- ==================================================
DROP TRIGGER IF EXISTS TRG_ESTOQUE_PEDIDO ON ITEM_PEDIDO;
DROP FUNCTION IF EXISTS ATUALIZAR_ESTOQUE_COMPRA() CASCADE;
DROP TRIGGER IF EXISTS TRG_ESTOQUE_COMPRA ON ITEM_COMPRA;
DROP FUNCTION IF EXISTS ATUALIZAR_ESTOQUE_PEDIDO();

-- ==================================================
-- ============ FUNÇÕES DE REMOÇOES ===================
-- ==================================================
DROP FUNCTION IF EXISTS REMOVER_CLIENTE(INT);
DROP FUNCTION IF EXISTS REMOVER_PRODUTO(INT);
DROP FUNCTION IF EXISTS REMOVER_PEDIDO(INT);
DROP FUNCTION IF EXISTS REMOVER_COMPRA(INT);

-- ==================================================
-- ============ DROP RELATÓRIO =========================
-- ==================================================
DROP TRIGGER IF EXISTS TRG_CALCULAR_TOTAL_PEDIDO ON ITEM_PEDIDO;
DROP TRIGGER IF EXISTS TRG_CALCULAR_TOTAL_COMPRA ON ITEM_COMPRA;
DROP TRIGGER IF EXISTS TRG_DEFINIR_VALOR_UNITARIO ON ITEM_PEDIDO;
DROP TRIGGER IF EXISTS TRG_EMAIL_CLIENTE ON CLIENTE;
DROP TRIGGER IF EXISTS TRG_TELEFONE_FUNCIONARIO ON FUNCIONARIO;
DROP TRIGGER IF EXISTS TRG_PROCESSAR_PEDIDO_COMPOSTO ON ITEM_PEDIDO;

-- ==================================================
-- ============ DROP FUNC VALIDAÇÕES ==================
-- ==================================================
DROP FUNCTION IF EXISTS VERIFICAR_ESTOQUE_COMPOSICAO_RECURSIVO(INT, INT);
DROP FUNCTION IF EXISTS VERIFICAR_ESTOQUE_COMPOSICAO_RECURSIVO(INT, NUMERIC);
ALTER TABLE PRODUTO DROP COLUMN ID_PRODUTO_COMPOE;
ALTER TABLE PEDIDO ADD COLUMN OBSERVACAO TEXT;

