-- ==================================================
--   ================ VIEWS ===========================
-- ==================================================

CREATE OR REPLACE VIEW VW_CLIENTES_ATIVOS AS
SELECT * FROM CLIENTE WHERE ATIVO = TRUE;

CREATE OR REPLACE VIEW VW_FUNCIONARIOS_ATIVOS AS
SELECT * FROM FUNCIONARIO WHERE ATIVO = TRUE;

CREATE OR REPLACE VIEW VW_FORNECEDORES_ATIVOS AS
SELECT * FROM FORNECEDOR WHERE ATIVO = TRUE;

CREATE OR REPLACE VIEW VW_PRODUTOS_ATIVOS AS
SELECT * FROM PRODUTO WHERE ATIVO = TRUE;

CREATE OR REPLACE VIEW VW_PEDIDOS_ATIVOS AS
SELECT * FROM PEDIDO WHERE ATIVO = TRUE;

CREATE OR REPLACE VIEW VW_ITENS_PEDIDO_ATIVOS AS
SELECT * FROM ITEM_PEDIDO WHERE ATIVO = TRUE;

CREATE OR REPLACE VIEW VW_COMPRAS_ATIVAS AS
SELECT * FROM COMPRA WHERE ATIVO = TRUE;

CREATE OR REPLACE VIEW VW_ITENS_COMPRA_ATIVOS AS
SELECT * FROM ITEM_COMPRA WHERE ATIVO = TRUE;

CREATE OR REPLACE VIEW VW_COMPOSICOES_ATIVAS AS
SELECT * FROM COMPOSICAO_PRONTA WHERE ATIVO = TRUE;

-- ==================================================
-- ==================================================
-- ==================================================
